#!/usr/bin/env python3
"""Translate ~/.life/routines/workflows.yaml -> dev-agent's workflows.yaml.

~/.life/routines/workflows.yaml is the canonical source-of-truth. dev-agent
has its own schema and sync_workflows.py. This bridge keeps ~/.life/ as the
single editing surface.

Mapping:
  routines[i].name     -> workflows[i].name
  routines[i].cron     -> workflows[i].schedule
  routines[i].prompt   -> workflows[i].goal
  routines[i].enabled  -> filter (only enabled routines emitted)
  routines[i].reads    -> prepended to goal as "Read first:" block

Skipped fields (dev-agent doesn't model them): output.

Usage:
  python ~/.life/routines/translate.py
  # then in dev-agent: python pipeline/sync_workflows.py
"""

from __future__ import annotations

from pathlib import Path
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML not installed. Run: pip install pyyaml")

CANONICAL = Path.home() / ".life" / "routines" / "workflows.yaml"
DEV_AGENT = Path.home() / "projects" / "dev-agent" / "workflows.yaml"
TIMEZONE = "Europe/Dublin"


def render_goal(routine: dict) -> str:
    parts = []
    reads = routine.get("reads") or []
    if reads:
        parts.append("Read first (in order):")
        for p in reads:
            parts.append(f"  - ~/.life/{p}")
        parts.append("")
    parts.append(routine["prompt"].strip())
    return "\n".join(parts)


def translate() -> dict:
    if not CANONICAL.exists():
        sys.exit(f"Canonical config missing: {CANONICAL}")

    src = yaml.safe_load(CANONICAL.read_text()) or {}
    routines = src.get("routines") or []

    out_workflows = []
    for r in routines:
        if not r.get("enabled", False):
            continue
        out_workflows.append(
            {
                "name": r["name"],
                "goal": render_goal(r),
                "schedule": r["cron"],
                "timezone": TIMEZONE,
            }
        )
    return {"workflows": out_workflows}


def main() -> None:
    target = translate()
    enabled_count = len(target["workflows"])

    header = (
        "# AUTO-GENERATED by ~/.life/routines/translate.py\n"
        "# Edit the canonical config at ~/.life/routines/workflows.yaml, then re-run translate.py.\n"
        "# Do NOT edit this file by hand.\n\n"
    )
    payload = yaml.safe_dump(target, sort_keys=False, allow_unicode=True)
    DEV_AGENT.write_text(header + payload)

    print(f"Wrote {DEV_AGENT}")
    print(f"  enabled routines: {enabled_count}")
    if enabled_count == 0:
        print("  (no routines enabled — nothing for dev-agent to sync yet)")
    print("\nNext: cd ~/projects/dev-agent && python pipeline/sync_workflows.py")


if __name__ == "__main__":
    main()
