#!/usr/bin/env python3
"""System upkeep — updates last_updated dates and surfaces inferred gaps.

Phase 5.3: keeps system docs honest as the tree evolves.

What it does:
  1. For each ~/.life/domains/*.md, if the file has changed since its
     YAML `last_updated:` value (by git mtime), bump that date to today.
  2. Scan system/proposals.md for `Status: new` entries with explicit
     "Why it matters" hints, summarize them into system/gaps.md under a
     dated "## Inferred from proposals" section (idempotent — same day's
     section is replaced).
  3. Print a human-readable summary of what changed.

Usage:
  python3 ~/.life/system/refresh.py
  python3 ~/.life/system/refresh.py --dry-run
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
import sys
from pathlib import Path

LIFE = Path.home() / ".life"
DOMAINS = LIFE / "domains"
PROPOSALS = LIFE / "system" / "proposals.md"
GAPS = LIFE / "system" / "gaps.md"

DATE_FMT = "%Y-%m-%d"
INFERRED_HEADER = "## Inferred from proposals"


def _git_mtime(path: Path) -> dt.date | None:
    """Return the last commit date for a file (None if untracked)."""
    try:
        out = subprocess.run(
            ["git", "-C", str(LIFE), "log", "-1", "--format=%cs", "--", str(path.relative_to(LIFE))],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        if not out:
            return None
        return dt.date.fromisoformat(out)
    except (subprocess.CalledProcessError, ValueError):
        return None


def _fs_mtime(path: Path) -> dt.date:
    return dt.date.fromtimestamp(path.stat().st_mtime)


def refresh_domain_dates(today: dt.date, dry_run: bool) -> list[tuple[Path, str, str]]:
    """For each domain file, update YAML last_updated to today if file is newer.

    Returns list of (path, old_value, new_value).
    """
    changes: list[tuple[Path, str, str]] = []
    for md in sorted(DOMAINS.glob("*.md")):
        text = md.read_text(encoding="utf-8")
        m = re.search(r"^last_updated:\s*(\S+)", text, flags=re.MULTILINE)
        if not m:
            continue
        current = m.group(1)
        # Heuristic: bump if filesystem mtime is more recent than declared date.
        try:
            current_date = dt.date.fromisoformat(current)
        except ValueError:
            current_date = dt.date.min
        if _fs_mtime(md) > current_date:
            new_text = re.sub(
                r"(?m)^last_updated:.*$",
                f"last_updated: {today.isoformat()}",
                text,
                count=1,
            )
            if not dry_run:
                md.write_text(new_text, encoding="utf-8")
            changes.append((md, current, today.isoformat()))
    return changes


def extract_new_proposals() -> list[tuple[str, str, str]]:
    """Return list of (slug, lens, why) for `Status: new` proposal entries."""
    if not PROPOSALS.exists():
        return []
    text = PROPOSALS.read_text(encoding="utf-8")
    out: list[tuple[str, str, str]] = []
    # split into entries by ### heading
    entries = re.split(r"^###\s+", text, flags=re.MULTILINE)
    for entry in entries[1:]:
        first_nl = entry.find("\n")
        if first_nl < 0:
            continue
        slug = entry[:first_nl].strip()
        body = entry[first_nl + 1 :]
        if not re.search(r"\*\*Status:\*\*\s*new", body, flags=re.IGNORECASE):
            continue
        lens_m = re.search(r"\*\*Lens:\*\*\s*(\S+)", body)
        why_m = re.search(r"\*\*Why it matters:\*\*\s*([^\n]+)", body)
        lens = lens_m.group(1) if lens_m else "?"
        why = why_m.group(1).strip() if why_m else ""
        out.append((slug, lens, why))
    return out


def update_gaps_from_proposals(today: dt.date, dry_run: bool) -> int:
    """Idempotently replace today's `## Inferred from proposals` section in gaps.md."""
    new_props = extract_new_proposals()
    if not new_props:
        return 0
    if not GAPS.exists():
        return 0
    text = GAPS.read_text(encoding="utf-8")
    section_lines = [
        "",
        f"{INFERRED_HEADER} ({today.isoformat()})",
        "",
        "Auto-generated by system/refresh.py from `Status: new` proposals.",
        "These are heuristic inferences — promote real gaps into the main list above by hand.",
        "",
    ]
    for slug, lens, why in new_props:
        section_lines.append(f"- **{lens}** — {slug} — {why}")
    new_section = "\n".join(section_lines) + "\n"

    # Replace any prior auto-inferred section, else append.
    pattern = re.compile(rf"\n{re.escape(INFERRED_HEADER)}.*?(?=\n## |\Z)", flags=re.DOTALL)
    if pattern.search(text):
        new_text = pattern.sub(new_section, text)
    else:
        new_text = text.rstrip() + "\n" + new_section

    if not dry_run:
        GAPS.write_text(new_text, encoding="utf-8")
    return len(new_props)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    today = dt.date.today()

    print(f"refresh — {today.isoformat()}\n")

    date_changes = refresh_domain_dates(today, args.dry_run)
    if date_changes:
        print(f"Updated last_updated on {len(date_changes)} domain file(s):")
        for path, old, new in date_changes:
            print(f"  {path.name}: {old} -> {new}")
    else:
        print("All domain last_updated dates are current.")

    n = update_gaps_from_proposals(today, args.dry_run)
    if n:
        print(f"\nUpdated gaps.md inferred section with {n} proposal(s).")
    else:
        print("\nNo new proposals to infer from.")

    if args.dry_run:
        print("\n--dry-run: no files written.")


if __name__ == "__main__":
    main()
