"""System upkeep — updates last_updated dates and surfaces inferred gaps.

Reads the instance root from `lifekit.core.paths.life_root()` (override with
LIFEKIT_ROOT env var).
"""

from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

from ..core.paths import life_root

INFERRED_HEADER = "## Inferred from proposals"


def _fs_mtime(path: Path) -> dt.date:
    return dt.date.fromtimestamp(path.stat().st_mtime)


def refresh_domain_dates(today: dt.date, root: Path, *, dry_run: bool = False) -> list[tuple[Path, str, str]]:
    changes: list[tuple[Path, str, str]] = []
    domains = root / "domains"
    if not domains.exists():
        return changes
    for md in sorted(domains.glob("*.md")):
        text = md.read_text(encoding="utf-8")
        m = re.search(r"^last_updated:\s*(\S+)", text, flags=re.MULTILINE)
        if not m:
            continue
        current = m.group(1)
        try:
            current_date = dt.date.fromisoformat(current)
        except ValueError:
            current_date = dt.date.min
        if _fs_mtime(md) > current_date:
            new_text = re.sub(
                r"(?m)^last_updated:.*$",
                f"last_updated: {today.isoformat()}",
                text,
                count=1,
            )
            if not dry_run:
                md.write_text(new_text, encoding="utf-8")
            changes.append((md, current, today.isoformat()))
    return changes


def extract_new_proposals(root: Path) -> list[tuple[str, str, str]]:
    proposals = root / "system" / "proposals.md"
    if not proposals.exists():
        return []
    text = proposals.read_text(encoding="utf-8")
    out: list[tuple[str, str, str]] = []
    for entry in re.split(r"^###\s+", text, flags=re.MULTILINE)[1:]:
        nl = entry.find("\n")
        if nl < 0:
            continue
        slug = entry[:nl].strip()
        body = entry[nl + 1 :]
        if not re.search(r"\*\*Status:\*\*\s*new", body, flags=re.IGNORECASE):
            continue
        lens_m = re.search(r"\*\*Lens:\*\*\s*(\S+)", body)
        why_m = re.search(r"\*\*Why it matters:\*\*\s*([^\n]+)", body)
        lens = lens_m.group(1) if lens_m else "?"
        why = why_m.group(1).strip() if why_m else ""
        out.append((slug, lens, why))
    return out


def update_gaps_from_proposals(today: dt.date, root: Path, *, dry_run: bool = False) -> int:
    gaps = root / "system" / "gaps.md"
    if not gaps.exists():
        return 0
    new_props = extract_new_proposals(root)
    if not new_props:
        return 0
    text = gaps.read_text(encoding="utf-8")
    section_lines = [
        "",
        f"{INFERRED_HEADER} ({today.isoformat()})",
        "",
        "Auto-generated by `lifekit refresh` from `Status: new` proposals.",
        "These are heuristic inferences — promote real gaps into the main list above by hand.",
        "",
    ]
    for slug, lens, why in new_props:
        section_lines.append(f"- **{lens}** — {slug} — {why}")
    new_section = "\n".join(section_lines) + "\n"
    pattern = re.compile(rf"\n{re.escape(INFERRED_HEADER)}.*?(?=\n## |\Z)", flags=re.DOTALL)
    new_text = pattern.sub(new_section, text) if pattern.search(text) else text.rstrip() + "\n" + new_section
    if not dry_run:
        gaps.write_text(new_text, encoding="utf-8")
    return len(new_props)


def run(*, dry_run: bool = False, root: Path | None = None) -> dict:
    root = root or life_root()
    today = dt.date.today()
    date_changes = refresh_domain_dates(today, root, dry_run=dry_run)
    inferred = update_gaps_from_proposals(today, root, dry_run=dry_run)
    return {"date_changes": len(date_changes), "inferred_gaps": inferred, "root": str(root)}


def main() -> None:
    result = run()
    print(f"date updates: {result['date_changes']}")
    print(f"inferred gaps in gaps.md: {result['inferred_gaps']}")


if __name__ == "__main__":
    main()
