"""Emit lifekit's canonical routines/workflows.yaml into a LangGraph-compatible
workflow file consumed by a LangGraph cron sync script.

Target schema (LangGraph cron, as used by All-Hands-AI/style sync scripts):

    workflows:
      - name: <stable id>
        goal: <prompt text>
        schedule: "<crontab>"
        timezone: <IANA tz>

Only routines with `enabled: true` are emitted. The lifekit canonical schema
fields `reads` and `output` are folded into the goal prompt as preamble.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from ..core.paths import life_root

DEFAULT_TIMEZONE = "Europe/Dublin"


def _render_goal(routine: dict[str, Any]) -> str:
    parts: list[str] = []
    reads = routine.get("reads") or []
    if reads:
        parts.append("Read first (in order):")
        for p in reads:
            parts.append(f"  - ~/.life/{p}")
        parts.append("")
    parts.append((routine.get("prompt") or "").strip())
    return "\n".join(parts).strip()


def translate(canonical: dict[str, Any], *, timezone: str = DEFAULT_TIMEZONE) -> dict[str, Any]:
    routines = (canonical or {}).get("routines") or []
    out_workflows: list[dict[str, Any]] = []
    for r in routines:
        if not r.get("enabled", False):
            continue
        out_workflows.append(
            {
                "name": r["name"],
                "goal": _render_goal(r),
                "schedule": r["cron"],
                "timezone": timezone,
            }
        )
    return {"workflows": out_workflows}


def emit(target: Path, *, root: Path | None = None, timezone: str = DEFAULT_TIMEZONE) -> tuple[Path, int]:
    """Read ~/.life/routines/workflows.yaml, translate, write to `target`.

    Returns (target_path, enabled_count).
    """
    root = root or life_root()
    src = root / "routines" / "workflows.yaml"
    if not src.exists():
        raise FileNotFoundError(f"canonical workflows missing at {src}")
    canonical = yaml.safe_load(src.read_text()) or {}
    rendered = translate(canonical, timezone=timezone)

    header = (
        "# AUTO-GENERATED by `lifekit emit langgraph-workflows`.\n"
        "# Edit the canonical config at ~/.life/routines/workflows.yaml then re-run the emitter.\n"
        "# Do NOT edit this file by hand.\n\n"
    )
    payload = yaml.safe_dump(rendered, sort_keys=False, allow_unicode=True)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(header + payload, encoding="utf-8")
    return target, len(rendered["workflows"])
